schedules:
- cron: "0 1 * * *"
  displayName: '1 AM Duplicate File'
  branches:
    include:
    - main
  always: true

trigger: none

pool:
  name: 'YourAgentPoolName'

steps:
- checkout: self
- script: |
    powershell -File $(Build.SourcesDirectory)/ `
    PowerShellScripts/scripts/DuplicateFile.ps1
  displayName: 'Duplicate File'



